### ISSUE TITLE
docs: 📚 Create showcase for form field usage in Storybook

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#124]
# Stories

As a user of the Synergy Design System I want to have a demo which shows how to build html forms using Synergy components.

As a developer of the Synergy Design System I want to have a demo to make sure that the created form field behaves as expected.

As a developer of the Synergy Design System I want to have a demo in a separate package to validate that the SDS can be flawlessly used as an external library. 

# Acceptance critera

 - status of the form field is submitted via the form data when triggering the submit action
 - data binding is working
 - reference to SDS package is working
 - Figma example are used as reference

**Comment by schilchSICKAG** [comment]
See also #142 and #143.

**Comment by klaarseSICKAG** [comment]
blocked by https://github.com/SickDesignSystem/design/issues/41
