### ISSUE TITLE
feat: ✨ Add basic css reset for the component library

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#13]
**Description**:

As a design system developer, I want to make sure basic styling of webcomponent `hosts` like margins or paddings are respected even when using a hard css reset like `* { margin: 0; padding: 0 }` that unfortunately seems to be still quite common in some applications.

**Rationale**:

Instead of some traditional baselines for HTML-Elements (like when using `normalize.css`), hard CSS resets may still be used in applications. Those reset types will change the display of our SDS components, too. The provided reset in this file can optionally be loaded into an application to preserve the behavior of the original components.

**Comment by reichst1SICKAG** [comment]
You might look at https://andy-bell.co.uk/a-more-modern-css-reset/ for inspiration and updated reset.
