### ISSUE TITLE
fix: 🤔 Vendorism does not draw all dependencies for tag component

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#168]
# Checklist

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: all

# Description

As a developer of the Synergy Design System, I want to vendor the `tag` component. This fails because the `icon-button` is a dependency, but does not seem to be added when vendorism is run.

# Steps to reproduce

- Create a new branch from main
- Run `pnpm i -r && pnpm build`
- Run `pnpm vendor.get` in the components package
- Add `tag` to the components array in `vendorism.js`
- Run `pnpm vendor.set` in the components package

Expected outcome:

- src/components/tag folder is created with all vendored files
- src/components/icon-button folder is created with icon-button.component.ts, as it is a dependency

Actual outcome:

- src/components/tag folder is created with all vendored files
- src/components/icon-button folder is **not** created, the dependency is not catched.

**Comment by kirchsuSICKAG** [comment]
I tested this behavior again and the issue seems fixed (probably via #191). 
I added the *tag* in the vendorism script and after the vendor.set command a *tag* folder with all its necessary files as well as an *icon-button* folder with the needed files were created.
