### ISSUE TITLE
fix: 🤔 Tests are issuing a "multiple versions of lit loaded" warning in console

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#173]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: all

# Component

The issue arises when using the following component(s): all

# Description

When using tests, I noticed that there where multiple warnings about multiple lit includes. As the tests use the bundle, it seems we are really loading multiple lit versions. 

# Current behavior:

- When running tests, there is a warning that we include multiple versions of lit

# Wanted behavior:

- We should aim to just use a single version of lit.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] The error should be gone
- [ ] We must make sure to only use one single version of lit to prevent clashes and maybe even lower the bundle size.

**Comment by kirchsuSICKAG** [comment]
I moved the part with the "multiple lit versions" when using storybook into another ticket, because this problem can currently not be resolved. For more information see #233
