### ISSUE TITLE
docs: 📚 explain package scripts

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#197]
# Description

All scripts in all package.json files should be explained.

# Rationale

As a developer of Synergy the package scripts are very important action triggers. I need to know which are important to me and which are only used by CI.

**Comment by mariohamann** [comment]
Could you make more concrete for which ones you're missing information?

I think everything besides `start`, `lint`, `build`, `test`, `release` and `chromatic` is documented in either the `README` of the package or the `CONTRIBUTING.md` in root.

There's not a big difference between CI and not CI. You could run I believe every script locally. Some are mainly used by CI (`release` and `chromatic`) but they could be used locally, too.

**Comment by klaarseSICKAG** [comment]
- vendor (without suffix)
- build.release
- release
- release.angular|.react|.vue
- start


Also, I think it is a good idea to have all scripts explained in one single file. Just to get a quick overview...
