### ISSUE TITLE
docs: 📚 cleanup stories - use attribute interaction only where applicable

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#199]
# Description

All stories provide the ability to change attributes, properties, etc.
This is a great feature if it really has an effect.
There are stories, though, where this feature is not attached. These are thoses who use static html rendering. e.g. the button-variant story.

# Rationale

As a stakeholder of Synergy and user of the Storybook stories I am confused if changing the attributes doesn't work.

**Comment by schilchSICKAG** [comment]
Done while cleaning up the `syn-switch` branch.
