### ISSUE TITLE
docs: 📚 improve stories by using  `generateTemplate` method everywhere

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#216]
# Description

Update all stories to use the `generateTemplate` method in the render call

# Rationale

Not using this method in a story means that the property controls are not working for this story (e.g. using the disabled switch will not affect the component with disable status). Therefore we disabled all controls for the non-default stories for the moment.
Also it is nicer for some stories to use the table mechanism of the `generateTemplate` .
For example this icon-button story would look like this:

![Image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/01cf0075-1eb0-431f-8600-bf92b18434a4)

instead of this:

![Image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/09717171-089f-4cde-8f35-1e6125f991bb)

Example code for this would be: 

`export const Sizes: Story = {
  parameters: {
    controls: { exclude: ['size'] },
    docs: {
      description: {
        story: generateStoryDescription('icon-button', 'sizes'),
      },
    },
  },
  render: (args: unknown) => generateTemplate({
    args,
    axis: {
      x: {
        name: 'size',
        type: 'attribute',
        values: ['small', 'medium', 'large'],
      },
    },
  }),
};`

**Comment by klaarseSICKAG** [comment]
according to @mariohamann we should have another look at it and do a refinement on that.
