### ISSUE TITLE
chore: 🔧  add browsers list

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#222]
# Description

The browsers list defines which browser versions are supported by the project.

# Rationale

We as maintainers have a defined baseline about supported browsers to make sure only available features are used.

# Acceptance criteria

- [x] provide baseline for components, tokens and css packages
- [ ] document in storybook
- [x] lint against the definitions
- [x] baseline: last 2 majors NOT DEAD

**Comment by reichst1SICKAG** [comment]
Feedback from the website dev team, which browsers they support:

We compile everything to ES2022.
https://compat-table.github.io/compat-table/es2016plus/ --> 2022 features

We had the following list for quite some time:
last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major versions
last 2 iOS major versions
Firefox ESR

not IE 9-10 
not IE 11 
not ios_saf 15.2-15.3
