### ISSUE TITLE
chore: 🔧 Storybook is issuing a "multiple versions of lit loaded" warning in console

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#233]
# Checklist (for the issue creator)

- [ ] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [ ] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: all

# Component

The issue arises when using the following component(s): all

# Description

When developing new components and running Storybook the warning message appears in the console, that multiple lit versions are included.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] The error should be gone
- [ ] We must make sure to only use one single version of lit to prevent clashes and maybe even lower the bundle size

**Comment by kirchsuSICKAG** [comment]
This issue can currently not be resolved!
In our docs package we are using _@mariohamann/wc-storybook-helpers_ as dev dependency. This package has _lit 2.6.1_ as dependency and _@open-wc/lit-helpers ^0.5.1_.
The lit version we could update by ourself, but the @open-wc/lit-helpers has currently no version, which supports lit 3 but only lit 2. Currently this [issue ](https://github.com/open-wc/open-wc/issues/2713) and this [pull request](https://github.com/open-wc/open-wc/pull/2723) are still open, which address the problem. We need to wait for them to be closed.

**Comment by schilchSICKAG** [comment]
Fixed via new version of `@mariohamann/wc-storybook-helpers`.

**Comment by mariohamann** [comment]
As @kirchsuSICKAG I could fix it for my own package, but not for `@open-wc/lit-helpers`. I've created a patch for it.
