### ISSUE TITLE
chore: 🔧 QA for form elements

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#260]
# Story

As a maintainer of Synergy I want to make sure that all input fields are working in a form context with and without Framework wrappers.

# Acceptance criteria

- [x] add e2e tests in playwright
- [x] check submitted data
- [x] check reset data
- [x] check valid / invalid states
- [x] validate bindings
- [x] runs in CI
- [x] use one page object for 
- [x] create a _private/form-test project: build FW projects and start a webserver for each
- [x] test on chrome, webkit, firefox

**Comment by schilchSICKAG** [comment]
Blocked by:

- https://github.com/synergy-design-system/design/issues/27
- #124 
- #142 
- #143 
- #209
