### ISSUE TITLE
research: evaluate accessibility errors in components

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#266]
# Description

As a synergy user I want all components to fulfill accessibility requirements. 
Currently there are accessibility errors in the components. 

# Acceptance criteria

- [x] find all components with accessibility errors (can be achieved via storybook`s accessibility tab)
- [x] propose solutions for all errors

**Comment by klaarseSICKAG** [comment]
see https://github.com/orgs/synergy-design-system/discussions/285
