### ISSUE TITLE
feat: ✨ Add utility classes for typography

### ISSUE THREAD

**Issue by reichst1SICKAG** [synergy-design-system/synergy-design-system#269]
# Checklist (for the issue creator)

- [x] I have looked at the documentation site and was not able to find the required feature.
- [x] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Story

As a user of the Synergy Design System, I would like to use typographic styles for headline and body text in a easy way so that my product uses the generally valid styles.

Figma branch: https://www.figma.com/file/bZFqk9urD3NlghGUKrkKCR/branch/4oqUjJbgNpMsX7fqfgOMyl/Synergy-Digital-Design-System?type=design&node-id=104%3A235&mode=design&t=LdKsFz2sUGWhh0kP-1

# Acceptance criteria

- [ ] All DoD items successfully completed
- [x] check the generated tokens from branch feat/add-text-styles from Figma
- [x] Create a new package with the name that fit future usecases
- [x] Create classes instead of tokens synchronization
- [x] Create documentation in Storybook (e.g. Readme, Changelog, Story for all typographic items) 
- [x] Use typography for Storybook stories
- [x] Offer a css file for basic styling
- [ ] Make sure to offer a singular css token for each font size that does **NOT** include font-weight, but makes sure that current variables are utilized correctly. See below for details:

## Token structure

Given the following JSON:

```json
  "body": {
    "x-small": {
      "regular": {
        "value": {
          "fontFamily": "{font.sans}",
          "fontWeight": "{font-weight.normal}",
          "fontSize": "{font-size.x-small}",
          "lineHeight": "{line-height.normal}"
        },
        "type": "typography"
      }
    }
  }
```

the following token should be created:

```css
:root {
  --syn-body-x-small: var(--syn-font-size-x-small)/var(--syn-line-height-normal) var(--syn-font-sans);
}
```

**Comment by reichst1SICKAG** [comment]
Hi @schilchSICKAG and @mariohamann 

would you like to take a look at the ticket here and add/adapt it so that it can be refined more easily.

Thanks
Stefan

**Comment by schilchSICKAG** [comment]
I have just created a first draft for an RFC for this at https://github.com/orgs/synergy-design-system/discussions/278. Please have a look and discuss @synergy-design-system/dev.

**Comment by schilchSICKAG** [comment]
As discussed with @mariohamann and @LeaLeRose, we will provide generic css helper functions for font weights, e.g. something like `.syn-bold` and `.syn-semi-bold` instead of the low level tokens for body copy.

**Comment by reichst1SICKAG** [comment]
Sounds good with the helpers.
Also the `typography` prefix was removed from the tokens int the branch already.

**Comment by schilchSICKAG** [comment]
> Sounds good with the helpers. Also the `typography` prefix was removed from the tokens int the branch already.

Hey @reichst1SICKAG, I already added a branch some time ago, which uses an older version of the typo tokens. You can see what I did there here: https://github.com/synergy-design-system/synergy-design-system/blob/feat/269-add-css-utility-package/packages/css/src/modules/typography.css.

I will update it when the merge of https://github.com/synergy-design-system/synergy-design-system/pull/318 is done

**Comment by schilchSICKAG** [comment]
I have just updated the branch to use the new tokens and add the mentioned utility classes for bold fonts. You can see the result at https://github.com/synergy-design-system/synergy-design-system/blob/feat/269-add-css-utility-package/packages/css/src/modules/typography.css.

**Comment by reichst1SICKAG** [comment]
I built the package and looked at the `dist` folder. 
This looks very good. 
Do we need to test this on a plain HTML file? Or is the `_private/vanilla-demo` using this? (Open sans is not loaded in the demo)

Also I was wondering about the inline woff2 font files. 
We don't use italic in any styles, so maybe remove them for about 60KB less filesize? We can keep them as woff2 in the fonts folder if somebody really needs it.

Also we need to inline-add the semibold font, to have all 3 weights there.

**Comment by schilchSICKAG** [comment]
> I built the package and looked at the `dist` folder. This looks very good. Do we need to test this on a plain HTML file? Or is the `_private/vanilla-demo` using this? (Open sans is not loaded in the demo)

Hey @reichst1SICKAG, thanks for the feedback. I am currently not using it anywhere currently, because dev is still not finally setteled. When the styles are fine for all persons, we will have to find a fitting name, create real README instructions, link it to storybook and finally, add templates for the utility classes (e.g. via https://storybook.js.org/docs/api/doc-block-typeset#fontsizes if it is applyable with our stuff).

> Also I was wondering about the inline woff2 font files. We don't use italic in any styles, so maybe remove them for about 60KB less filesize? We can keep them as woff2 in the fonts folder if somebody really needs it.
> 
> Also we need to inline-add the semibold font, to have all 3 weights there.

Will sure do this, this was just for demos sake. Would also like to discuss what you think about using default fonts instead of web-fonts to lessen the load burdon for downloads slightly. The question for me is, if Open-Sans really is required for a good and holistic feel during usage in Web-Applications.

**Comment by schilchSICKAG** [comment]
As discussed today:

- No form styling will be shared
- Demos have to be reverted
- Stories for form styling will be reverted
- Table will get deleted
- Creation of text styles have to be changed to match the new expections

**Comment by schilchSICKAG** [comment]
Currently onhold because of ongoing research in #365

**Comment by schilchSICKAG** [comment]
Doing this will be part of https://github.com/synergy-design-system/synergy-design-system/issues/455
