### ISSUE TITLE
fix: 🤔 syn-input with type number does not emit change event in firefox on release of mouse if max or min value was reached

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#295]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: latest

# Component

The issue arises when using the following component(s):
- syn-input with type=number

# Environment

The issue occurred with the following operating system(s): all
The issue occurred in the following browser(s): Firefox

# Description
**! This bug only occurs in Firefox !**

Bug can be reproduced with following code example:
`<syn-input id="number" @syn-change=${() => console.log('change')} @syn-input=${() => console.log('input')} type="number" min="0" max="10" value="0"></syn-input>`

When pressing down the increment stepper until the max value is reached and therefore the increment button is disabled, after releasing the mouse, the change event is not fired, if the mouse is over the disabled increment button. See gif 1:
![firefoxNumberStepperBug](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/8c055d05-3082-436e-b5c0-9b65dcd16cfc)

For chrome, safari and edge everything works fine and the change event is released. See gif 2:
![chromeNumberStepperBug](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/1838524f-0a7d-4866-b289-5dbf7aff96fe)

## Details
This is because firefox has another handling for disabled HtmlButton elements. They do not emit an `pointerup` event, if the button is disabled. The other browsers do. 
Our longpress handling depends on this behavior, that a `pointerup` event is emitted. We only emit the `syn-change` event after the click is release -> pointerup.
A possible fix would be to not use the "disabled" attribute of the HTMLButton, but to only use a `disabled` class, which adds a disabled styling to the stepper buttons

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] syn-change event is emitted after mouse release on disabled button on ALL browsers

**Comment by klaarseSICKAG** [comment]
no stakeholder feedback until now. reopen if issue arises again.

**Comment by kirchsuSICKAG** [comment]
Just tested this again with firefox and with the newest version of firefox, this behavior is no longer available and therefor fixed 🎉
