### ISSUE TITLE
feat: ✨ Create syn-header

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#299]
# Checklist (for the issue creator)

- [ ] I have looked at the documentation site and was not able to find the component.
- [ ] I have looked into the Figma boards and was not able to find the component.
- [ ] I would be willing to provide a PR for this component.

# Story

As a user of the Synergy Design System, I would like to have a syn-header so that I can brand and control my application

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Create demo for Framework wrappers
- [ ] The `syn-header` does not interact with slotted navigations initially.
- [ ] Slots are prepared for future use (e.g. for navigations).
- [ ] When developers use the `syn-header`, the SICK logo should be visible per default.

**Comment by klaarseSICKAG** [comment]
blocked by https://github.com/synergy-design-system/design/issues/46

**Comment by schilchSICKAG** [comment]
@schilchSICKAG: Create a follow up ticket for interaction with navigation items!
