### ISSUE TITLE
fix: 🤔 adjust synergy form template

### ISSUE THREAD

**Issue by LeaLeRose** [synergy-design-system/synergy-design-system#310]
# Description

Some fixes for the templates: 

1. The Contact template had a language mix in the sub-headlines.

- [x] "Your question concerns?" = semantically broken question
- [x] "Describe your question." = calls for action
- [x] "Your contact details" = neutral description, but with a strange colon in the end.

We decided to change this into: 

- [x] "Topic"
- [x] "Question"
- [x] "Contact Details"

This fit a lot better to SICK's straightness.

- [x] All Subheadlines should be 20px and bold
- [ ] adding a description with the docs.tokens for forms
- [x] Tablet view is not needed in the docs view of the Templates

# Acceptance criteria

- [ ] All DoD items successfully completed

**Comment by schilchSICKAG** [comment]
I have added the required changes, however the docs tokens are not used in Figma yet, so I was unable to use them. I went with a static text for the time being, as we also currently do with the labels of the inputs themselfs.
