### ISSUE TITLE
feat: ✨ syn-drawer

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#311]
# Story

As a user of the Synergy Design System, I would like to have a drawer so that content can be shown or hidden.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] ~~Added drawer to wrapper demos~~
- [x] Content can overlayed
- [x] Drawer should be closable
- [x] Should accept any content
- [x] Should be able to animate
- [x] Should be able to position in all 4 orientations
- [x] Should be able to define a max-size (width or height)
- [x] Should be able to provide a parent element
- [x] Navigation with Keyboard

**Comment by klaarseSICKAG** [comment]
design: https://github.com/synergy-design-system/design/issues/56

**Comment by schilchSICKAG** [comment]
I have opted to NOT add the drawer to the framework wrappers, as this will be done when we tackle the side-navigation
