### ISSUE TITLE
docs: 📚 AppShell template(s)

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#316]
# Description

As a user of synergy I want to have an easy start with an application which looks like a typical SICK app without spending too much time.

# Rationale

Show how to orchestrate a typical application with app-shell components in Storybook.
If meaningful provide more than one template: e.g. for a fixed sidebar, dynamic sidebar, with and without top-bar navigation, with and without step-navigation

# Acceptance criteria
- [x] template for vanilla, vue, react, ng
- [x] 5 different variants
- [x] Have a storybook demos
- [x] template should contain header, top-bar navigation, side-bar, footer (text only)
- [x] SICK logo should be in the header
- [x] Shrinked contend

**Comment by klaarseSICKAG** [comment]
design: https://github.com/synergy-design-system/design/issues/47

**Comment by schilchSICKAG** [comment]
Blocked until Header and Navigation components are available

**Comment by schilchSICKAG** [comment]
Can only be estimated after design ticket for templates is finished (https://github.com/synergy-design-system/design/issues/78)
