### ISSUE TITLE
fix: 🤔syn-select is missing a visual invalid state

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#328]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 1.7.0

# Component

The issue arises when using the following component(s): syn-select

# Environment

The issue occurred with the following operating system(s): macos
The issue occurred in the following browser(s): chrome

# Description

If used in a form and the status gets invalid it doesn't show a red border like the other input elements.

Example:
```html
<syn-select data-user-invalid></data-user-invalid>
```

# Acceptance criteria

- [ ] All DoD items successfully completed

**Comment by reichst1SICKAG** [comment]
It is only missing in the Docs as an example. It exists in the component and is visible in the Handoffs


![Image](https://github.com/synergy-design-system/synergy-design-system/assets/142008971/7182cf1f-8796-4c72-8dd4-f1dc738380f6)

![Image](https://github.com/synergy-design-system/synergy-design-system/assets/142008971/d51218a2-cb1c-416b-b9b2-04a8f4b6f987)

**Comment by klaarseSICKAG** [comment]
duplicate of #329
