### ISSUE TITLE
fix: 🤔 Broken tokens in themes light.css and dark.css

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#332]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: all tokens versions

# Component

The issue arises when using the following component(s): -

# Environment

The issue occurred with the following operating system(s): -
The issue occurred in the following browser(s): -

# Description

The themes of the tokens package have invalid tokens for  `--syn-input-background-color-hover`, `--syn-input-background-color-focus` and `--syn-input-background-color-disabled`. The value of this tokens should be `--syn-input-background-color` with a **`-`** instead of `--syn-input-background.color` with a **`.`**.

![image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/c351244a-6eab-4a3e-92b9-86d51720ac4c)

Because of that our hover state of e.g. the syn-input is broken, because the background color token can't be found.

![opacityBeiHover](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/eff98022-26a9-472a-84d8-2e3827080a64)

# Acceptance criteria

- [x] All DoD items successfully completed
- [x] The tokens have valid names
- [x] Automatic check for valid state (e.g. stylelint)
- [x] Check if all tokens are valid

**Comment by reichst1SICKAG** [comment]
The Tokens are looking correct.

![Image](https://github.com/synergy-design-system/synergy-design-system/assets/142008971/f8646d51-251b-4898-8d6d-0937823a60ba)

**Comment by kirchsuSICKAG** [comment]
Yes, it`s a problem of our converter, which creates the light.css and dark.css
