### ISSUE TITLE
fix: 🤔 Wrapper do not provide all properties from the component

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#333]
# Checklist (for the issue creator)

- [ ] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [ ] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: all

# Component

The issue arises when using the following component(s): possibly all

# Environment

The issue occurred with the following operating system(s): -
The issue occurred in the following browser(s): -

# Description

The wrapper do not provide all properties from the components. All properties which do not have the `@property` tag but only a `get` and / or `set` they do not appear in the wrapper.

![image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/e69741bf-1b91-4978-810d-e99d6dcd1621)

E.g. the syn-input has the `valueAsNumber` property, it appears in the custom-elements.json, but none of the wrappers (vue, angular, react) provide it.

 

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Add documentation to wrapper docs how to use set/get properties

**Comment by schilchSICKAG** [comment]
As with https://github.com/synergy-design-system/synergy-design-system/issues/473 for [version 2.0](https://github.com/synergy-design-system/synergy-design-system/pull/448), we will not expose any methods anymore on the wrappers themself. Therefore, this ticket will be closed.
