### ISSUE TITLE
feat: ✨ handle CSS reset

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#336]
# Checklist (for the issue creator)

- [ ] I have looked at the documentation site and was not able to find the required feature.
- [ ] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Story

As a user of the Synergy Design System, I would like to use synergy components along with a global css reset

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Handle css resets for slotted elements in some way

**Comment by reichst1SICKAG** [comment]
This is an interesting Idea: https://jaydenseric.com/blog/forget-normalize-or-resets-lay-your-own-css-foundation
But the Author discarded it already.

More: 
https://piccalil.li/blog/a-more-modern-css-reset/
https://frontendmasters.com/blog/still-no-css-reset/
https://github.com/h5bp/main.css
