### ISSUE TITLE
docs: 📚 show property documentation in storybook

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#337]
# Description

get/set properties are missing the documentation in Storybook

# Rationale

Documentation is part of the webcomponents.json but it is not shown in storybook. Instead the documentation field is empty.

![Image](https://github.com/synergy-design-system/synergy-design-system/assets/44837861/46f8b33b-6734-49fe-ac96-bd0c6d46d1d1)

**Comment by klaarseSICKAG** [comment]
when generating the webcomponents.json properties the description field must be flagged properly

**Comment by schilchSICKAG** [comment]
This is now visible in Storybook, see attached screenshot.

![Image](https://github.com/user-attachments/assets/e26ef517-6023-4a65-84fc-d244daf30e50)
