### ISSUE TITLE
chore: 🔧 Storybook build does not work on chromatic with safari 

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#344]
# Description
Our chromatic tests are breaking since we activated safari as browser.
The safari builds are throwing errors:

![image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/0a018562-97ca-456b-89e0-db139d558901)

![image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/4af51f82-4bc6-4d6f-aea4-14ed43bf50dc)

https://www.chromatic.com/test?appId=64f819d70a69cb8728e06daf&id=65dc560f5ae2799c49a9da41

# Rationale
In addition to run our screenshot tests also on safari, we need to fix this problem first.

**Comment by klaarseSICKAG** [comment]
![Image](https://github.com/synergy-design-system/synergy-design-system/assets/44837861/ca824df4-aec7-40fe-9a00-9a5d1ff2ac57)



![Image](https://github.com/synergy-design-system/synergy-design-system/assets/44837861/f94f82e8-a733-4203-b2ec-ea31b94fe718)
