### ISSUE TITLE
fix: 🤔 One Firefox test is failing

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#355]
# Version

The bug occurred with the following version of the component library: 1.10.0

# Component

The issue arises when using the following component(s): <syn-select>

# Environment

The issue occurred with the following operating system(s): -
The issue occurred in the following browser(s):Firefox

# Description

Firefox tests are deactivated because of this failing test.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Either the single failing test is excluded
- [ ] Or the test is fixed
- [ ] In either Synergy or Shoelace

**Comment by mariohamann** [comment]
Could you make the ticket a bit more sharper? Which text? Why didn't we deactivate only this single test for FireFox? Is it a problem of the tests or is it really a bug (`fix`) or a testing issue (`chore`)?

**Comment by klaarseSICKAG** [comment]
we didn't deactivate it. It was deactivated by shoelace. Have a look at https://github.com/shoelace-style/shoelace/blob/next/web-test-runner.config.js line 26

**Comment by klaarseSICKAG** [comment]
Created an issue at Shoelace: https://github.com/shoelace-style/shoelace/issues/1915

**Comment by kirchsuSICKAG** [comment]
Fixed with #411
