### ISSUE TITLE
docs: 📚 improvement of developer docu

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#356]
# Description

### Framwork wrapper
everything which is stated here should be done for every framework:

- add the explanation for the naming convention for each framework (e.g. in Vue we always have `SynVue` as prefix for the component name and the  rest is added via camelcase: syn-button = SynVueButton, syn-icon-button = SynVueIconButton)
- [x] angular
- [x] vue
- [x] react

- add explicit link to our demo repository with the information, that an example usage in this framework can be seen there
- [x] angular
- [x] vue
- [x] react

- add example for an input with e.g. SynChangeEvent and usage of the `target.value` for typescript
```
onChange={( e: SynChangeEvent) => someMethod((e.target as SynInput).value)}
```
- [x] angular
- [x] vue
- [x] react

- add example with component from the framework wrapper package and type of the components package
```
import {SynButton} from '@synergy-design-system/react';
import {type SynButton as SynButtonType} from '@synergy-design-system/components';

const buttonRef = useRef<SynButtonType>(null)
<SynButton ref={buttonRef}>
My Button
</SynButton>
```
- [x] angular
- [x] vue
- [x] react

### Angular wrapper
- [x] add angular 16 to the compatibility statement: `We are currently supporting Angular version 16 and 17.`
- [x] add information, that typescript version >=5 is needed, otherwise there will be typescript compilation errors

### Icons
- [x] nowhere is explained, that the assets-package needs to be installed and how it is installed. this should be added at the icon story documentation
```
npm i @synergy-design-system/assets
```
- [x] add readme and changelog of assets package to storybook

### Icon-button
- [x] nowhere is explained, that the assets-package needs to be installed and how it is installed. this should be added at the icon story documentation (maybe just a link to the icon docu)

### General
- [x] add figma links to all components / packages

# Rationale

As a user I want a good documentation, so it`s easy for me to get started with synergy

**Comment by klaarseSICKAG** [comment]
see https://deagxjira.sickcn.net/jira/projects/SYN/issues/SYN-6
