### ISSUE TITLE
research: 🧐 Evaluate how to make css utilities available when installing components

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#365]
# Checklist (for the issue creator)

- [x] I have looked at the documentation site and was not able to find the required feature.
- [x] I have looked into the Figma boards and was not able to find the required feature.
- [x] I would be willing to provide a PR for this feature.

# Story

As a developer using the Synergy Design System, I would like to have just one package that must be installed so that I am able to boostrap applications easier. I also do not want to think of keeping the components and tokens package in sync.

As a developer maintaining the Synergy Design System, I want to make sure that the design tokens and components package are related closely with each other, so there are no errors when just one of the dependencies is updated.

---

# Rationale

While thinking about the implementation of https://github.com/orgs/synergy-design-system/discussions/278 (which will be delayed because of this) and https://github.com/synergy-design-system/synergy-design-system/issues/269, we talked about the explicitly needed coupling between the new styles package and components, as well as tokens.

Parts of the team see this as a critical problem, as the styles package would depend on those too packages, which **could** lead to problems after installation. After having a look at our current solution (which is to install tokens and components every time), we came to the conclusion that this is not only a problem with the new styles package, but a general one that we also have currently.

---

## Problem scope 1 - Package Sync:

- A project is bootstrapped and installs the latest versions of `@synergy-design-system/components` and `@synergy-design-system/tokens`.
- A new component includes changes in both the components and tokens package. Both packages are released with new minor versions.
- The user updates `@synergy-design-system/components`, but does not update the tokens.
- His system is now broken, as newly created tokens are not available in his old version of `@synergy-design-system/tokens`.

The same would be true when only updating the tokens, but not the components package.

## Problem scope 2 - Bootstrapping:

After installation, we currently need to load multiple different style sheets to make the system able to work:

### Current version

```javascript
import '@synergy-design-system/tokens/dist/themes/light.css`;

// Possibly:
// import '@synergy-design-system/tokens/dist/themes/dark.css`;

import '@synergy-design-system/components/themes/utilities.css';

// Later on, when https://github.com/synergy-design-system/synergy-design-system/issues/269
// is done:
import '@synergy-design-system/styles/utilities/body.css';
import '@synergy-design-system/styles/utilities/typo.css';

// Finally, load some components
import '@synergy-design-system/components';
```

### Possible variants:

```javascript
// Possibility 1: Reexport in components:
import '@synergy-design-system/components/dist/themes/light.css`;

// Possibility 2: tokens is a dependency, just install through it:
import '@synergy-design-system/tokens/dist/themes/light.css`;

// Possibility 3: As discussed in the original styles package,
// but now directly in components
import '@synergy-design-system/components/themes/light.css`;

// Possibility 3:
// Utilities are drawn from components as a bundle, too.
import '@synergy-design-system/components/themes/utilities.css';

// Possibility 4: Moving the original styles packages contents to components completely
// gives way to having the "just install" approach and all needed subpackages with one line:
import '@synergy-design-system/components/themes/all.css`;

// Finally, load some components
import '@synergy-design-system/components';
```

### Suggested variant:

```javascript
import '@synergy-design-system/components/themes/all.css`;

// Finally, load some components
import '@synergy-design-system/components';
```

---

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Tokens and Components are still available as their own modules
- [ ] Components should include Tokens as dependency.
- [ ] A release of tokens should trigger a release of components and the framework wrappers
- [ ] Storybook is adjusted to reflect these changes
- [ ] The documentation is adjusted to reflect these changes
- [ ] Framework-Wrappers are adjusted to reflect these changes
- [ ] The demo projects are adjusted to reflect these changes

**Comment by mariohamann** [comment]
Different solutions were discussed, how to handle a `styles` package, where to place classes for `syn-headline` etc. During that ideas were discussed, how the installation process could be made more easy to reduce the amount of `imports` from CSS and JS.

# Questions
1. What happens with `utilities.css` (contains things that have to be in LightDOM e. g. for the `syn-alert`)? → Should be part of `components` package.
2. What happens with `fouc.css`? → Should be part of `components` package, as it heavily depends on existing components.
3. What happens with future CSS "components", e. g. for `table-cell`? → Could be part of `components` package – but as this needs new dependencies (PostCSS) and adds additional folders, this could weaken our clear structure there.
4. What's the role of the `tokens` package? → `styles` and `components` are both dependent on it. Some changes there should lead to updates in the dependents as well (e. g. new tokens, renamed tokens).
5. How can the installation process be made easier to reduce `imports`?


# Proposals
1. There is a separate `styles` package, but everything is additionally incorporated into the components package.
2. There is a separate `styles ` package, but everything is additionally incorporated into a new package that includes everything.
3. There is no separate `styles ` packages, everything is built and included in the components package.
4. There is a separate `styles ` package, that is not included in other packages.

# Solution
Were aiming for proposal `#4` which leads to a  new `styles` package. This package has a dependency on `tokens`. In addition we will add `tokens` as a dependency of `components` as well. This is needed, as both `components` and `styles` are highly dependent on a fitting theme from the tokens package, where all needed variables are available.

We will have to hardcode the package version of tokens into those packages in the form of `^1.2.2.`. This leads to the following:
- `npm i @synergy-design-system/components @synergy-design-system/styles` → This installs `tokens` as well. If one updates `@synergy-design-system/components`, this might bump the `tokens` package for `styles` as well. As long as there is no breaking change, this is no problem for `@synergy-design-system/styles`. As soon as there is a breaking change, `@synergy-design-system/styles` needs the new version as well.
- `npm i @synergy-design-system/components @synergy-design-system/styles @synergy-design-system/tokens` → Users are free to use the tokens in their app as well. As soon as they do that, they have to have a fitting version for `components` and `styles`. Semver should take care of that here.

To reduce dev effort, we won't offer a single package, that includes everything, as we first want to ensure, that the process above works. But we will offer `index.css` files, that include all needed styles of every folder.


The following would do the same:

## Combination
```js
import '@synergy-design-system/tokens/light.css';
import '@synergy-design-system/components';
import '@synergy-design-system/components/index.css';
import '@synergy-design-system/styles/index.css';
```

## Seperation
```js
import '@synergy-design-system/tokens/light.css';
import '@synergy-design-system/components';
// import '@synergy-design-system/components/index.css';
import '@synergy-design-system/components/utilties.css';
import '@synergy-design-system/components/fouc.css';
// import '@synergy-design-system/styles/index.css';
import '@synergy-design-system/styles/prose.css';
import '@synergy-design-system/styles/typography.css';
import '@synergy-design-system/styles/table-cell.css';
```

This allows users to explicitly decide what they want to include from the bundle or where they want more control / aka smaller bundle size.

## Additional note
We're going with the wording `styles` for the new package. This wording is used in other design systems as well, see [Lyne by SBB](https://lyne-storybook.app.sbb.ch/?path=/docs/styles-list--docs) and [Solid by Union Investment](https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/styles-sd-chip--docs)

**Comment by schilchSICKAG** [comment]
I am fine with this approach. Just created a new ticket at #455 that will hold the work for this ticket.
