### ISSUE TITLE
feat: ✨ adjust padding for syn-menu + syn-dropdown checkmarks

### ISSUE THREAD

**Issue by LeaLeRose** [synergy-design-system/synergy-design-system#368]
# Component

I suggest to add the feature to the following component: syn-menu-item

# Story

The current menu has always the same padding on the left side. Current Padding is huge, since the Component can have a Select checkmark. The improvement would be, the menu noticed if the menu has a Select function inside and if no item has a select icon we reduce the padding

**Comment by klaarseSICKAG** [comment]
consider pull request for shoelace
