### ISSUE TITLE
research: 🧐 Evaluate chromatic visual test addon for storybook

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#371]
# Description

We should evaluate Chromatics new [Storybook Visual Tests Addon](https://www.chromatic.com/blog/visual-tests-addon/). This makes it possible to run chromatic tests directly in Storybook, making it uneccessairy to push to CI/CD just to compare the new code changes.

# Rationale

This may be helpful for faster iteration times. It should not be necessary to trigger the whole pipeline for failing snapshot tests. 

# Acceptance criteria

- [ ] plugin is added to storybook config
- [ ] tests can be triggered manually
- [ ] add dev docu: warn that this might lead to excessive quota usage

**Comment by mariohamann** [comment]
I think this should have a special look on if it is possible to screenshot only selected stories. Otherwise this could be quite expensive. 😆
