### ISSUE TITLE
feat: ✨ syn-dropdown opening Chevron 

### ISSUE THREAD

**Issue by LeaLeRose** [synergy-design-system/synergy-design-system#373]
# Component

I suggest adding the feature to the following component: syn-dropdown

In the Syn-dropdown we are using a chevron that only shows in one direction. When the Menu is opening the chevron should change its direction, to identify that it is opening. 

# Acceptance criteria

- [ ] All DoD items successfully completed

**Comment by klaarseSICKAG** [comment]
Is this really necessary? Implementation is quite complicated...

**Comment by reichst1SICKAG** [comment]
In the HTML default element the arrow doesn't change.
I also looked at other Design Systems, and most also don't change the icon.

-> Won't Do
