### ISSUE TITLE
docs:📚 add codepen link to stories

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#376]
# Story
As a user of synergy I want to fiddle with the code for experimentation purposes.

# Description

There is a custom [CodePen Plugin](https://storybook.js.org/addons/storybook-addon-codepen/) that makes it possible to add stories into a code-pen. We would have to add static assets, as seen in https://codepen.io/schilchSICKAG/pen/MWxLpdr to make it work. This makes it possible to easily spin up a demo pen and try out the code in another environment.

# Rationale

As a DEVELOPER using the Synergy Design System, I want to have an easy way to create samples for broken features or have a playground to test the shown features of a story.

# Acceptance criteria

- [x] Provide Codepen button for each story
- [x] Styles must be loaded automatically
- [x] Code must be loaded automatically (unpkg)
- [x] Changes in the fiddle result in changed rendering
- [ ] Add workflow to Jira / github issue: go into Storybook -> codepen -> savelink -> provide link
- [x] register bundled icon-library under default (registerIconLibrary('default',...) so the codepen user can simply use syn-icon

**Comment by schilchSICKAG** [comment]
Stopped for now as it would need much work to make it work correctly

**Comment by klaarseSICKAG** [comment]
https://storybook.js.org/addons/storybook-addon-export-to-codesandbox/

**Comment by klaarseSICKAG** [comment]
https://storybook.js.org/addons/@stackblitz/storybook-addon-stackblitz

**Comment by schilchSICKAG** [comment]
> https://storybook.js.org/addons/storybook-addon-export-to-codesandbox/

This is no longer supported, see https://github.com/microsoft/fluentui-storybook-addons. Also, works with react only.

**Comment by klaarseSICKAG** [comment]
custom solution: https://github.com/synergy-design-system/synergy-design-system/pull/552
works well enough.
