### ISSUE TITLE
fix: 🤔 button: missing padding

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#388]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: current

# Component

The issue arises when using the following component(s): syn-button

# Environment
Angular 17.3
The issue occurred with the following operating system(s): MacOS
The issue occurred in the following browser(s): Chrome

# Description

When using a translate pipe for the button text, the padding is lost until button is clicked.

<syn-button routerLink="/publications/create">{{ 'app.common.new-publication' | translate }}</syn-button> 

# Acceptance criteria

- [ ] Margin is always set correctly

**Comment by klaarseSICKAG** [comment]
origin: Jira SYN-4

**Comment by schilchSICKAG** [comment]
Not reproducible when using a simple pipe like described in https://angular-book.dev/ch11-02-creating-translate-pipe.html. May be a problem specific to the translation module used. I checked back with the internal devs and have to debug in their environment

**Comment by schilchSICKAG** [comment]
https://github.com/shoelace-style/shoelace/issues/1987

**Comment by schilchSICKAG** [comment]
Will be documented in #449

**Comment by schilchSICKAG** [comment]
This cannot be fixed as the reason for this is specific to shoelaces use of `slotchange` events. Like pointed out at the Shoelace repository, the problem with buttons will go away with web-awesome as it will not utilize those type of `slotchange` listeners anymore.

However, this problem may still lead to errors in the future, so we will document them in #449.
