### ISSUE TITLE
chore: 🔧 Evaluate and eventually upgrade to Chromatic@3

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#396]
# Description

Chromatic has just released a [new major version](https://www.chromatic.com/blog/chromatic-3/).

# Rationale

As a developer working with the Synergy Design System, I want to make sure my dependencies are up to date. I also want to participate in the latest features and improvements Chromatic has to offer. See the linked blog post for more features.

**Comment by klaarseSICKAG** [comment]
refers to https://github.com/synergy-design-system/internal/issues/65

**Comment by schilchSICKAG** [comment]
Chromatic 3 is more of a feature set, with the main feature being TurboSnap. As we already have a ticket for evaluating this, closing as a duplicate.
