### ISSUE TITLE
feat: ✨ Angular: Allow two way data binding component wrappers

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#397]
# Checklist (for the issue creator)

- [x] I have looked at the documentation site and was not able to find the required feature.
- [x] I have looked into the Figma boards and was not able to find the required feature.
- [x] I would be willing to provide a PR for this feature.

# Story

As a developer using `@synergy-design-system/angular` package, I want to make use of [angulars two way binding](https://angular.io/guide/two-way-binding) to make reactive bindings work. Currently, only `ngForms` is supported.

# Acceptance criteria

- [x] All DoD items successfully completed
- [x] Two way component databinding works as described in the angular documentation
- [ ] The Angular Demo is adjusted to show the usage of bindings
- [x] The Wrapper documentation is adjusted to show how the binding can be used.

**Comment by klaarseSICKAG** [comment]
origin: SYN-6
