### ISSUE TITLE
feat: ✨ link css

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#405]
# Checklist (for the issue creator)

- [x] I have looked at the documentation site and was not able to find the required feature.
- [x] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Story

As a user of the Synergy Design System, I would like to have support for links in a document.

# Acceptance criteria

- [x] All DoD items successfully completed
- [x] Styling for links are provided in the styles package (default, hover, visited, etc.)
- [x] icons have same color as text
- [ ] add entry to migration guide

**Comment by klaarseSICKAG** [comment]
@mariohamann mentioned that it would be a good idea to have just a proper css class intead of a web-component

**Comment by reichst1SICKAG** [comment]
Check if css could resolve all icon variants as show by solid: https://solid-design-system.fe.union-investment.de/x.x.x/storybook/?path=/docs/components-sd-link--docs

**Comment by schilchSICKAG** [comment]
I am not sure what you mean with icon-variants, but solids implementation is a full blown web-component.

**Comment by mariohamann** [comment]
I think it was more about "could we solve all variants that e. g. Solid shows with CSS as well?". And I think that would be great. I'm not really happy, that `sd-link` is a web component and would have tried as CSS if we would have had that in mind at this point already.

**Comment by reichst1SICKAG** [comment]
Yes, that was the case. I think we solved it in the design-sync. 
-> Component for Figma, CSS for Dev

**Comment by klaarseSICKAG** [comment]
blocked by design

**Comment by reichst1SICKAG** [comment]
Design in Figma is ready to be looked at. 
Tokens are also in place in the linked branch.
