### ISSUE TITLE
fix: 🤔 add "Menu" in syn-prio-nav to translatable strings and deprecate `priority-menu-label`

### ISSUE THREAD

**Issue by mariohamann** [synergy-design-system/synergy-design-system#407]
# Component

`syn-prio-nav`

# Description

Currently the word `menu` is not part of the translation files. Therefore everyone would have to translate theirself by adding a prop. Instead we should use the translation files to make this translatable, so that it can switch depending on `lang=de` etc.

In addition the attribute should be deprecated, so that we can remove it in the next major release.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] syn-prio-nav uses translations (german and english)
- [ ]  `priority-menu-label` is deprecated
- [ ] deprecation info shows up in types and Storybook and informs that it will be removed in the next Major Release (@deprecated)

**Comment by schilchSICKAG** [comment]
I am still not sure if it is really wise to go this way. When using fixed strings from the translation files, we are bound to use `en` and `de` only (currently). This means that a user that has an __already translated__ main application using his locale "cn" would see an application that is completely rendered in chinese - except for the string "Menu" that we hard coded. One could argue that we could just provide translations for chinese. However, this does not scale as there are so many languages out there and we do certainly not want to maintain a large pack of language files.

My suggestion would be:

1. Leave the property alive to make it possible to translate into languages we do not support.
2. Add the "Menu" string to the german and english translations files
3. Use this static translation as a default if no `priority-menu-label` attribute was set.

This would it make possible for us to automatically set Menu string in each languages we officially offer support for and override on a per need basis for foreign languages we do not have any support for.

@mariohamann 
@kirchsuSICKAG 
@klaarseSICKAG

**Comment by mariohamann** [comment]
But the question was not if they need this for translations but if they would need the label for a different wording instead of "Menu". I can't really read from your answer, what the result was in this regard.

Changing the translation behaviour is a completely different issue and would have a much broader impact, as you said. We're currently investigating in [Solid to allow instance specific i18n](https://github.com/solid-design-system/solid/issues/852), which would go into that direction.

**Comment by schilchSICKAG** [comment]
After discussion with @mariohamann and the rest of the dev team, we agree that we need a holistic solution for the underlying problem for all future and present components. Therefore, we chose to implement this fix as suggested by Mario and strife for a global solution in another ticket.
