### ISSUE TITLE
feat: ✨ SynPrioNav: Adjust syn-prio-nav shrinking mechanism

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#410]
# Checklist (for the issue creator)

- [x] I have looked at the documentation site and was not able to find the required feature.
- [ ] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Component

I suggest to add the feature to the following component: syn-prio-nav

# Story

Currently the syn-prio-nav shows the priority menu only, if there is no space left for any navigation item. If there is space for one navigation item, it shows this navigation item. See following image for the current behavior:
![image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/ad1fc069-371a-4980-af4e-456aad34618e)

From UX perspective the priority menu only should also be shown if there is only one space left for one navigation item. So in the image above the first syn-prio-nav should look the same like the second with the priority menu only.

# Acceptance criteria

- [x] All DoD items successfully completed

- [x] syn-prio-nav shows priority menu only, if there is space for just one navigation item left
- [x] docs are updated in doc tokens about the behavior

**Comment by reichst1SICKAG** [comment]
Need to check of there is Design Work to do.
