### ISSUE TITLE
feat: ✨ provide accessible solution for validation

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#412]
# Checklist (for the issue creator)

- [ ] I have looked at the documentation site and was not able to find the required feature.
- [ ] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Component

I suggest to add the feature to the following component: all input elements

# Story

As a user I want to get informed about invalid input in an accessible way.

Have a look at https://shoelace.style/getting-started/form-controls#inline-form-validation

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Provide documentation for validation of form-controls (see shoelace docs: https://shoelace.style/getting-started/form-controls)
- [ ] Wrapper component (e.g. <syn-validation><syn-input></syn-input></syn-validation>) takes care of when to trigger the validation (e.g. on change or input)
- [ ] Adjust framework demos to make use of it.
- [ ] Add note in Angular Limitations that ngNativeValidate must be set
- [ ] Try adding this feature into Shoelace

**Comment by klaarseSICKAG** [comment]
internal reference: SYN-10
