### ISSUE TITLE
feat: ✨ global size setting

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#431]
# Component

I suggest to add the feature to the following component: all input components

# Story

As a user of the Synergy Design System, I would like to set the size of the used input elements only once somewhere global so I don't need to set the size for each element separately.

# Acceptance criteria

- [ ] All DoD items successfully completed

**Comment by klaarseSICKAG** [comment]
ditched due to complexity. e.g. SSR, typings, general default value overrides, etc.

**Comment by schilchSICKAG** [comment]
And still possible, not that hard at all and done :)
