### ISSUE TITLE
feat: ✨ Create Table Cell Component

### ISSUE THREAD

**Issue by eileenwegner** [synergy-design-system/synergy-design-system#441]
### Userstory

As a user of the Synergy Design System, I would like to use the table cell component that can be used as a building block for a table

### Acceptance criteria
- [ ] Provide CSS only
- [ ] Provide stories
- [ ] Provide template
- [ ] Provide architecture

**Comment by klaarseSICKAG** [comment]
blocked by https://github.com/synergy-design-system/synergy-design-system/issues/365
