### ISSUE TITLE
research: 🧐 Angular: Check how to better use syn-nav-item with routerLink directive

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#442]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 1.15.0

# Component

The issue arises when using the following component(s): syn-nav-item, syn-button

# Environment

The issue occurred with the following operating system(s): Any
The issue occurred in the following browser(s): Any

# Description

When using a component that may act as a link (like `syn-nav-item` or `syn-button`), the [Angular RouterLink directive](https://angular.io/api/router/RouterLink) will always trigger full page reloads when setting a `[routerLink]` property. This hapens because `routerLink` does only work completely with native `HTMLAnchor` elements.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Demo showing the problem is created on StackBlitz
- [ ] Possible workarounds are defined
- [ ] Possible fix is proposed

**Comment by xkabylgSICKAG** [comment]
I managed to get `routerLinkActive` to work as well with these two directives:

```ts
import { Directive, ElementRef, Host, Renderer2 } from '@angular/core';
import {
  Event,
  NavigationEnd,
  Router,
  RouterLink,
  RouterLinkActive,
} from '@angular/router';

@Directive({
  selector: 'syn-nav-item[routerLink]',
  standalone: true,
})
export class SynNavItemRouterLinkDirective {
  constructor(router: Router, @Host() routerLink: RouterLink) {
    routerLink['isAnchorElement'] = true;
    routerLink['subscription'] = router.events.subscribe((s: Event) => {
      if (s instanceof NavigationEnd) {
        routerLink['updateHref']();
      }
    });

    routerLink['applyAttributeValue']('tabindex', null);
  }
}

@Directive({
  selector: 'syn-nav-item[routerLinkActive]',
  standalone: true,
})
export class SynNavItemRouterLinkActiveDirective {
  constructor(
    element: ElementRef,
    renderer: Renderer2,
    @Host() routerLinkActive: RouterLinkActive,
  ) {
    const originalUpdate = routerLinkActive['update'].bind(routerLinkActive);
    routerLinkActive['update'] = () => {
      originalUpdate();

      queueMicrotask(() => {
        if (routerLinkActive.isActive) {
          renderer.setAttribute(element.nativeElement, 'current', 'true');
        } else {
          renderer.removeAttribute(element.nativeElement, 'current');
        }
      });
    };
  }
}
```

**Comment by schilchSICKAG** [comment]
This is now part of our own angular demo at https://github.com/synergy-design-system/synergy-design-system/blob/main/packages/_private/angular-demo/src/directives/index.ts and https://github.com/synergy-design-system/synergy-design-system/blob/main/packages/_private/angular-demo/src/app.component.html#L7
