### ISSUE TITLE
fix: 🤔 Playwright tests flaky

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#446]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 1.17.1

# Component

The issue arises when using the following component(s): All

# Environment

The issue occurred with the following operating system(s): MacOS
The issue occurred in the following browser(s): Firefox + Webkit (Chrome never)

# Description

Our current Pipeline still breaks in ca. 30% - 50% of all cases. This makes working with branches harder than it has to, leading to various manual retriggers until tests run through.
Playwright tests as well as webtestrunner are affected.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] All tests run without flakiness and produce the same results with the same input

**Comment by klaarseSICKAG** [comment]
Timeboxed to 1 day.
Remove flaky browsers (per test) if it cant be fixed.

**Comment by kirchsuSICKAG** [comment]
Here an example for a broken pipeline test: https://github.com/synergy-design-system/synergy-design-system/actions/runs/8828796532/job/24238469290

![Image](https://github.com/synergy-design-system/synergy-design-system/assets/115139104/d7ce7173-250f-456c-b571-5276c5952ce9)
