### ISSUE TITLE
fix: 🤔 currentColor for headerButtons not working in header context

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#450]
# Version

The bug occurred with the following version of the component library: 1.16.0

# Component

The issue arises when using the following component(s): syn-header / syn-icon-button

# Description

If _syn-icon-button_ defines its color as _currentColor_, the color of the parent element should be used. But it isn't.
```html
<syn-header label="My App">
  <nav slot="meta-navigation" style="color: red">
    <syn-icon-button color="currentColor" name="apps" label="Apps"></syn-icon-button>
  </nav>
</syn-header>
````
# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Icon color matches the color of the parent element (in this case _red_)

**Comment by mariohamann** [comment]
This is not connected to the `syn-header`. It always only works by explicitly setting the collor on the `syn-icon-button´.

I just realized, that this is not documented and there's no example for that over here: https://synergy-design-system.github.io/?path=/story/components-syn-icon-button--colors

So this is more a documentation problem than a fix.

**Comment by schilchSICKAG** [comment]
I am not sure, but the [`currentcolor` documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword) implies the color is inherited. Is this maybe a bug in our implementation?

**Comment by mariohamann** [comment]
The color is re-set on the host of syn-icon-button. :)

**Comment by schilchSICKAG** [comment]
Usage Error, see comments :)
