### ISSUE TITLE
docs: 📚 Add documentation for vue components testing error

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#476]
# Description

When using the vue components in an application with `vitest` for testing, the tests are failing with following error: 

```
FAIL  src/components/HelloWorld.spec.ts [ src/components/HelloWorld.spec.ts ]
TypeError: Unknown file extension ".vue" for /test-apps/vue-ts/node_modules/@synergy-design-system/vue/src/components/SynVueBadge.vue
Serialized Error: { code: 'ERR_UNKNOWN_FILE_EXTENSION' }
```

# Rationale

As a vue developer I want to be able to use the synergy vue components withou failing tests.

# Proposal for documentation changes
### Using `vitest` for testing
When using our vue components in an application together with `vitest`, it leads to following error when running the tests:

```
FAIL  src/components/HelloWorld.spec.ts [ src/components/HelloWorld.spec.ts ]
TypeError: Unknown file extension ".vue" for /test-apps/vue-ts/node_modules/@synergy-design-system/vue/src/components/SynVueBadge.vue
Serialized Error: { code: 'ERR_UNKNOWN_FILE_EXTENSION' }
```
This error can be solved by adapting the `vitests.config.ts` in following way:

Vitest < 0.34.x
```
  test: {
    ...,
    deps: {
      inline: [/@synergy-design-system\/vue/]
    }
  }
```

Vitest >= 0.34.x

```
  test: {
    ...
    server: {
      deps: {
        inline: [/@synergy-design-system\/vue/]
      }
    },
  }
  ```

**Comment by schilchSICKAG** [comment]
We can add this as a recipe, however we have to make sure that we tell people this is not caused by our wrappers by themself, but with a long standing issue of vitest that happens also on `.css` files or images.
