### ISSUE TITLE
feat: ✨ add BEM methodology to guideline

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#548]
# Story

As a developer of the Synergy Design System, I would like to have a proper guideline for CSS structuring.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Add guideline that BEM should be used if meaningful (also show when to use BEM and when not)
- [ ] change table css structure to follow BEM

**Comment by schilchSICKAG** [comment]
Maybe we could also enforce it via https://www.npmjs.com/package/stylelint-selector-bem-pattern, as we are using stylelint anyways?
