### ISSUE TITLE
research: 🧐 check if react 19 still needs a wrapper layer

### ISSUE THREAD

**Issue by klaarseSICKAG** [synergy-design-system/synergy-design-system#568]
# Description

New React release supports Webcomponents natively.

# Rationale

**Comment by schilchSICKAG** [comment]
This was tested with a stackblitz example at https://stackblitz.com/edit/vitejs-vite-hprznn?file=src%2FApp.tsx. Long story short: It does not work out in the way it should. There are multiple problems when using the components (although they display correctly):

1. When using typescript, there are no type adjustments for the ts-compiler to make it know that the custom-elements are valid react elements. You will need typescript types for this in the forseeable future.
2. Custom event bindings are currently poorly documented (if at all). Also the examples stated in https://github.com/facebook/react/issues/29659 do not work with shoelace or synergy (see linked stackblitz).
