### ISSUE TITLE
fix: 🐛 syn-icon-button is not honoring 'currentColor' correctly

### ISSUE THREAD

**Issue by j-o-sh** [synergy-design-system/synergy-design-system#590]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 2.4.3 - and whatever is on the official storybook atm. ;) 

# Component

The issue arises when using the following component(s): <syn-icon-button>

# Description

`<syn-icon-button>` is documented to use `currentColor` as a default and as such to honor the inherited color of the parent DOM. In reality it declares its own host css as 
```css
:host {
    display: inline-block;
    color: var(--syn-color-neutral-600);
}
```

You can see the problem in [This CodePen](https://codepen.io/j-o-sh/pen/XWLZQzZ?editors=1110) as well.

# Acceptance criteria

- [x] When `color="currentColor" is set, the icon-button should inherit the color of the parent DOM element
- [x] This should be the same when no `color` attribute is set.
- [x] remove workaround in #450 

----

Also, I noticed there was already a similar (badly named but whatever) issue with #450 but I couldn't tell why that one was closed as _user error_ 😳

**Comment by klaarseSICKAG** [comment]
@j-o-sh thanks for reporting

vendored attribute is missing class map for currentColor

**Comment by schilchSICKAG** [comment]
Hey @j-o-sh, that was a good one, thank you for reporting it. Just created a fix for this, will land in a release in a couple of days.
