### ISSUE TITLE
fix:  🐛  Upgrade style-dictionary to new major version

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#591]
# Description

We currently use outdated versions of `style-dictionary` (3.9.2 -> 4.2.0) and `@tokens-studio/sd-transforms` (0.14.4 -> 1.2.3). There are [multiple incompatible configuration changes](https://v4.styledictionary.com/version-4/migration/) that mean we will need to spend more time with migration. It also means the token structure likely has to be changed or at least adopted (e.g. the CTI tokens will not be taken from the structure start path anymore, as documented at https://v4.styledictionary.com/version-4/migration/#cti-reliance).

# Rationale

We want to stay on the current version of style dictionary to make sure we receive the latest features. Also, the tokens-studio transforms will tie into Figma's Token-Studio much better with the lastest version.

# Acceptance criteria

- [x] upgrade core
- [x] upgrade style dictionary
- [x] upgrade matchers
- [x] upgrade external plugins
- [x] check if token structure must be updated

**Comment by reichst1SICKAG** [comment]
Token Studio also realeased a 2.0 major update: https://tokensstudio.featurebase.app/changelog/release-20
Main point is the W3C DTCG format support/update
