### ISSUE TITLE
fix: 🐛 syn-select wrong rendering order with container-type set on parent

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#612]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 2.7.2

# Component

The issue arises when using the following component(s): syn-select, syn-popup

# Environment

The issue occurred with the following operating system(s): all
The issue occurred in the following browser(s): all

# Description

Having a syn-select (or syn-popup) in a parent element with `container-type` set to something other than `normal` leads to a changed layout order rendering, so the listbox of the syn-select is behind other elements, which are not part of the parent element with `container-type` set.
![Image](https://github.com/user-attachments/assets/242a44d4-686c-4d0f-b37f-13a57f8dc439)

For an example see following codepen: https://codepen.io/kirchsuSICKAG/pen/KKjLGPz

The `container-type` creates a new stacking context. It is possible to get the listbox of the select above the other elements, if on the parent element with `container-type` a higher z-index is added. E.g via following css: 

```html
.container {
  container-type: inline-size;

 position: relative;
 z-index: 1;
}
```

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] Document workaround in "known issues" / limitations
- [x] create issue in shoelace

**Comment by kirchsuSICKAG** [comment]
Issue was added in shoelace. See: https://github.com/shoelace-style/shoelace/issues/2171

**Comment by schilchSICKAG** [comment]
Also: https://github.com/shoelace-style/shoelace/issues/2185
