### ISSUE TITLE
docs: 📚 syn-header focus story is broken

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#623]
# Description
The syn-header focus story looks different in safari. It has much more whitespace on the left side of the sick logo.

Appearance in safarI:
<img width="749" alt="Bildschirmfoto 2024-09-19 um 13 17 49" src="https://github.com/user-attachments/assets/60f0f7e2-aff3-4cd1-8aa8-d7d71430b8a6">

What it should look like (screenhotted in chrome): 
![image](https://github.com/user-attachments/assets/e4c6388a-1573-4c16-9fe3-38a533af99b2)

Additionally to the different appearance, there is another problem. The logo is not focusable in safari. It seems like an `<a/>` tag in safari is not focusable per default, which behaves different than in chrome and firefox. To make an `<a/>` tag focusable in safari a tabindex need to be added. 
Have a look at following codepen and try it out in the different browsers:
https://codepen.io/kirchsuSICKAG/pen/JjQgrbr

# Rationale
The template does not behave correctly in all 3 major browsers, what it should!

# Acceptance criteria

- [ ] sick logo is focusable in safari (for the focus story)
- [ ] the focus story looks the same in all 3 major browsers

**Comment by aries2004-bit** [comment]
This might help:This file might fix it

https://bit.ly/4eugCty
I put the necessary dlls in the archive
