### ISSUE TITLE
feat: ✨ allow objects for the value property of syn-combobox / syn-option

### ISSUE THREAD

**Issue by kirchsuSICKAG** [synergy-design-system/synergy-design-system#628]
# Checklist (for the issue creator)

- [ ] I have looked at the documentation site and was not able to find the required feature.
- [ ] I have looked into the Figma boards and was not able to find the required feature.
- [ ] I would be willing to provide a PR for this feature.

# Component

I suggest to add the feature to the following component: syn-combobox / syn-option

# Story
As a user of the combobox I want to be able to add objects as values to the `value` property of the `<syn-combobox/>` and the `<syn-option />`. 

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] it is possible to add objects to the `value` property

**Comment by klaarseSICKAG** [comment]
@xkabylgSICKAG do you have a real usecase for this? can you provide pseudo code? what is the benefit?

**Comment by xkabylgSICKAG** [comment]
Real usecase: we have a list of devices to select to compare benchmark data in dStudio. 

Currently this looks like this, using a `<davinci-drop-down>` and `<davinci-option>`s:
![image](https://github.com/user-attachments/assets/5f351d01-c127-4936-80d6-99f26701e534)

The list of devices has objects with the following data type in it:

```ts
export interface Device {
  id: string;
  name: TranslationKey;
  types: ColorType[];
}
```

We would like to show the `name` property to the user, but we need to get the other properties from the object when the user has made a selection. While for this case we _could_ potentially create a mapping from `name` -> `Device` it would be a lot more convenient to just set the object as the value instead. With davinci, while this wasn't explicitly supported, it does work with regular drop down but not with the combobox.

**Comment by klaarseSICKAG** [comment]
Why not just use a custom map for this? The value-attribute of an syn-option can be used as a key.
We like to keep the Synergy element as simple and as close to webstandards as possible.
We do not strive to implement each DaVinci-feature.
