### ISSUE TITLE
fix: 🐛 menu text in <syn-prio-nav> is not aligned with baseline of other text

### ISSUE THREAD

**Issue by xkabylgSICKAG** [synergy-design-system/synergy-design-system#630]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 2.9.0

# Component

The issue arises when using the following component(s): syn-prio-nav

# Environment

The issue occurred with the following operating system(s): all
The issue occurred in the following browser(s): all

# Description

https://codepen.io/xkabylgSICKAG/pen/qBeBreZ?editors=1110

![image](https://github.com/user-attachments/assets/a2dd42ea-b023-4810-a294-672cf4b94cab)

This can be fixed by setting `display: flex; align-items: center;` on the `::part(content-container)` of syn-nav-item, but the syn-nav-item inside the prio-nav isn't accessible to our applications.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] All text in the priority menu share a common baseline

**Comment by klaarseSICKAG** [comment]
@xkabylgSICKAG do you have a real usecase for this?

**Comment by xkabylgSICKAG** [comment]
@klaarseSICKAG 

It just looks ugly IMO, when the text hops up a few px when I resize the window. Doesn't seem intentional?

**Comment by schilchSICKAG** [comment]
Hi @xkabylgSICKAG, I do not see any jumps in the provided codepen. Am I missing something?

**Comment by xkabylgSICKAG** [comment]
@schilchSICKAG 
In the provided codepen I have created two prio navs and set the size of the elements to be so that you can see the issue without having to resize the window. If you manually adjust the size of the prio-nav using dev tools you can see that when it starts to show the "menu" text, that text is not rendered at the same baseline as the text was before resizing.

**Comment by schilchSICKAG** [comment]
Okay, I think I see what you mean. Thanks for the input, will have a look into this.

@klaarseSICKAG:

Just use the devtools to adjust the width to something really small, you will see the "more" link will have a visual jump when there is no more navitem visible (approx. 110px)
