### ISSUE TITLE
fix: 🐛 SynPrioNav: adding href to <syn-nav-item> in  <syn-prio-nav> results in bad text alignment

### ISSUE THREAD

**Issue by xkabylgSICKAG** [synergy-design-system/synergy-design-system#631]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 2.9.0

# Component

The issue arises when using the following component(s): syn-prio-nav, syn-nav-item

# Environment

The issue occurred with the following operating system(s): all
The issue occurred in the following browser(s): all

# Description

![image](https://github.com/user-attachments/assets/91c8bdf9-1520-44d2-ba2f-3624ce13e8e1)
https://codepen.io/xkabylgSICKAG/pen/MWNWmog

This can be fixed by adding the following css:

```css
syn-nav-item::part(base) {
  display: flex;
  align-items: center;
}
```

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] mixing buttons and links in a prio nav results in the same baseline alignment

**Comment by schilchSICKAG** [comment]
Hi @xkabylgSICKAG, good catch, will have a look into it in one of the next couple of days.

**Comment by xkabylgSICKAG** [comment]
@klaarseSICKAG I was experimenting with using the prio-nav as a sort of pseudo-tabs becase the tabs didn't really work for a bunch of other reasons (I might write up a ticket on that later...)

So what I tried to do was basically:

Link to Tab 1 | Link to Tab 2 | Button to create new tab

And it doesn't line up.

**Comment by schilchSICKAG** [comment]
Hi @xkabylgSICKAG,

The intention of the `<syn-prio-nav>` is to be used with `<syn-nav-item>` elements. Those have a special alignment because of the active marker used to indicate the given item with `<syn-nav-item current>`.

Maybe it would be better to tackle the problems that you have using the tabs as this seems to be a workaround you want to use?

**Comment by xkabylgSICKAG** [comment]
@schilchSICKAG

I guess, but I can add the `current` indicator to the non-links too. So the alignment should probably be the same regardless?

Is the behaviour intentionally supposed to be that the text moves when adding/removing a href-attribute? That feels very unexpected to me. For example, if I look at the [syn-prio-nav documentation](https://synergy-design-system.github.io/?path=/docs/components-syn-prio-nav--docs) all the examples doesn't have any `href`s, and will be buttons. When I go to implement it myself, and very likely use `href`s, the spacing won't look the same as in the examples.

**Comment by klaarseSICKAG** [comment]
You're right. The alignment should not be different when adding a href attribute. Good catch!
Regarding the syn-tab: please get in touch with us directly.
