### ISSUE TITLE
fix: 🐛 Icons do not scale with font-size when using `spriteSheet: true` for custom icon library

### ISSUE THREAD

**Issue by huberpaSICKAG** [synergy-design-system/synergy-design-system#649]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 2.10.1

# Component

The issue arises when using the following component(s): syn-icon

# Environment

The issue occurred with the following operating system(s): All
The issue occurred in the following browser(s): Chromium, Safari (Firefox not tested)

# Description

When using SVG sprite sheets as custom icon library the icons size does not scale with the font size of the `syn-icon` component. 
I use `svg2sprite-cli` to generate the sprite sheet from a given set of individual SVG icons. The library is registred using 
``` ts
registerIconLibrary('sprite', {
  resolver: (name) => `./assets/sprites/sprite.svg#${name}`,
  mutator: (svg) => {
    svg.setAttribute('fill', 'currentColor');
  },
  spriteSheet: true,
});
```

When adding `height=100%` and `width=100%` attributes to the `<use>` tag in the `syn-icon`'s shadow dom the icon scales correctly. Maybe these should be added to [icon.component.ts](https://github.com/synergy-design-system/synergy-design-system/blob/a63815aba7d158199b786ad7770782492ea403f8/packages/components/src/components/icon/icon.component.ts#L68)? 

Thanks in advance. 

P.S.: I also noticed that the code snippet in the [documentation on 'Sprite Sheet Usage'](https://github.com/synergy-design-system/synergy-design-system/blob/a63815aba7d158199b786ad7770782492ea403f8/packages/components/src/components/icon/icon.component.ts#L68) seems to be wrong (the first `resolver: (name) => {` must be deleted). 

# Acceptance criteria

- [ ] All DoD items successfully completed

**Comment by klaarseSICKAG** [comment]
@schilchSICKAG check if this can be solved with #641
