### ISSUE TITLE
fix: 🐛 SynRadioGroup: SynRadio elements not clickable when they have no value while using form validation

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#661]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [x] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: Any

# Component

The issue arises when using the following component(s): syn-radio-group, syn-radio

# Environment

The issue occurred with the following operating system(s): All
The issue occurred in the following browser(s): All

# Description

When using an `<syn-radio-group>` with required set to true, it is not possible to select `<syn-radio>` elements that do not have a value property set when clicking on the item the first time.

This can be seen at https://codepen.io/schilchSICKAG/pen/JjgOxyv?editors=1000 in Shoelace. I also created a Shoelace Issue for this at https://github.com/shoelace-style/shoelace/issues/2229.

# Acceptance criteria

- [ ] All DoD items successfully completed
- [ ] `<syn-radio>` elements should be clickable when there is no value set and `required` is set to true.

**Comment by klaarseSICKAG** [comment]
please ping shoelace devs again
