### ISSUE TITLE
chore: 🔧 Check Workflows with latest announced breaking changes

### ISSUE THREAD

**Issue by schilchSICKAG** [synergy-design-system/synergy-design-system#671]
# Description

As stated in https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/, Github Actions will soon deprecate the `ubuntu-latest` label. This means we will either

a) have to adjust the label or
b) make sure our jobs run fine with the new latest.

# Rationale

We do not want our jobs to fail.

**Comment by schilchSICKAG** [comment]
@kirchsuSICKAG, @klaarseSICKAG: Just tested it, works fine with the new "latest" Ubuntu 24. The only question is if we want to stick with the latest tag or want to pin the OS version in our jobs (which I did to test the new Ubuntu version).

When sticking with the latest tag (which I would recomment):

- We receive future updates automatically (like it is now).
- Will have to actively monitor if the latest tag is updated on Githubs side (will be roughly all 2 years or so)

When changing to a fixed image (e.g. `runs-on: Ubuntu-24.04`):
- More stable because it won´t change under the hood via foreign actions
- May not receive os updates automatically (e.g. there is no `runs-on: Ubuntu-24.x` as far as I know) -> Risk of image getting stale.
- We still have to manually check if there are newer images we are compatible with.

I have closed the attending PR https://github.com/synergy-design-system/synergy-design-system/pull/687 for know as I don´t think we want to merge this with the fixed version.

Let´s discuss this, but I think **we are fine for the time being** with our current CI setup :)

**Comment by kirchsuSICKAG** [comment]
I'm fine with sticking with the latest tag. 
Even if we forget to review the latest tag on github side, if the pipeline fails at some point we can just pin the ubuntu version then and investigate it at a later point, when we have more time for it.

**Comment by schilchSICKAG** [comment]
We decided to stay on the latest tag. I just closed the PR for this.
