### ISSUE TITLE
fix: 🐛 syn-side-nav indentation-story has no indentation

### ISSUE THREAD

**Issue by reichst1SICKAG** [synergy-design-system/synergy-design-system#708]
# Checklist (for the issue creator)

- [x] I have verified the bug exists in the latest version of `@synergy-design-system/components` (e.g. via `pnpm install @synergy-design-system/components`).
- [x] I can provide a simple, reproducible example of the issue (e.g. via code-sandbox or sample code, ...).
- [ ] I would be willing to provide a PR for this issue.

# Version

The bug occurred with the following version of the component library: 2.14.3

# Component

The issue arises when using the following component(s): syn-side-nav

# Environment

The issue occurred with the following operating system(s): macOS 15.1.1
The issue occurred in the following browser(s): Firefox 133

# Description

In the indentation story, there is no indentation visible
https://synergy-design-system.github.io/?path=/story/components-syn-side-nav--indentation&globals=viewport:defaultViewPort

## Storybook
![Image](https://github.com/user-attachments/assets/60ab4bb3-629e-4a48-8474-c07aecdb542c)

## Figma
![Image](https://github.com/user-attachments/assets/530ee072-7ed6-46d9-a442-4e81b0ebca6b)

# Acceptance criteria

- [ ] All DoD items successfully completed

**Comment by kirchsuSICKAG** [comment]
The indentation is only not visible on firefox. Needs to be investigated

**Comment by kirchsuSICKAG** [comment]
It seems that the handling of firefox differentiates from the other browsers here.
I guess it is related to the fact, that when using `getComputedStyle()` in firefox within a window with no presentation (e.g. display: none), it returns an empty string. For more information see the firefox note of https://caniuse.com/mdn-api_window_getcomputedstyle

The problem in our syn-side-nav is that we use another custom element (syn-drawer) in the component, which also needs time to be there, which results in this behavior. Changing the syn-drawer with any other custom elements resolves in the same result..
